import os
import pytest
import sqlite3
from fastapi.testclient import TestClient

# -----------------------------------------------------------------------
# Bug fix: removed hardcoded Windows absolute path.
# Now uses a portable relative path resolved to the project directory.
# -----------------------------------------------------------------------
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_TEST_DB = os.path.join(_THIS_DIR, "test_hr_automation.db")
os.environ["DATABASE_URL"] = f"sqlite:///{_TEST_DB}"
os.environ["LLM_PROVIDER"] = "mock"

# Clean up any previous test database before the test session
if os.path.exists(_TEST_DB):
    try:
        os.remove(_TEST_DB)
    except Exception:
        pass

from main import app
from database.db import get_db_connection

client = TestClient(app)


def test_health_endpoint():
    """Verifies GET /api/v1/health returns system status and DB connection validation."""
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"
    assert data["database_connected"] is True
    assert data["llm_provider"] == "mock"


def test_create_and_get_memory():
    """Verifies manually creating memory (POST /api/v1/memory) and retrieving (GET /api/v1/memory)."""
    payload = {
        "user_id": "usr_test_1",
        "session_id": "sess_test_1",
        "content": "User prefers morning interview slots",
        "memory_type": "long_term",
        "significance_score": 8
    }
    response = client.post("/api/v1/memory", json=payload)
    assert response.status_code == 201
    data = response.json()
    assert data["user_id"] == "usr_test_1"
    assert data["content"] == "User prefers morning interview slots"
    assert data["memory_type"] == "long_term"
    assert data["significance_score"] == 8
    assert "id" in data

    get_res = client.get("/api/v1/memory?user_id=usr_test_1")
    assert get_res.status_code == 200
    memories = get_res.json()
    assert len(memories) >= 1
    assert memories[0]["content"] == "User prefers morning interview slots"


def test_orchestrate_request_scheduling():
    """Verifies POST /api/v1/request routes scheduling requests to SchedulingAgent stub."""
    payload = {
        "user_id": "usr_test_1",
        "session_id": "sess_test_1",
        "text": "Please schedule a meeting with Alice tomorrow morning."
    }
    response = client.post("/api/v1/request", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert "request_id" in data
    assert data["intent"] == "Scheduling"
    assert data["confidence"] >= 0.7
    assert "Scheduling Agent" in data["response"]
    assert data["status"] == "SUCCESS"


def test_orchestrate_request_leave():
    """Verifies POST /api/v1/request routes leave queries to LeaveAgent stub."""
    payload = {
        "user_id": "usr_test_1",
        "session_id": "sess_test_1",
        "text": "I want to apply for vacation leave from Oct 10."
    }
    response = client.post("/api/v1/request", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "Leave"
    assert "Leave Agent" in data["response"]


def test_orchestrate_request_compliance():
    """Verifies POST /api/v1/request routes compliance queries to ComplianceAgent stub."""
    payload = {
        "user_id": "usr_test_1",
        "session_id": "sess_test_1",
        "text": "What is the remote work policy at ZeloraTech?"
    }
    response = client.post("/api/v1/request", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "Compliance"
    assert "Compliance Agent" in data["response"]


def test_orchestrate_request_clarification():
    """Verifies POST /api/v1/request routes ambiguous queries to ClarificationAgent."""
    payload = {
        "user_id": "usr_test_1",
        "session_id": "sess_test_1",
        "text": "Hello, please help."
    }
    response = client.post("/api/v1/request", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "Clarification"
    assert "Orchestrator: I'm not fully certain" in data["response"]


def test_audit_logs_retrieval():
    """Verifies GET /api/v1/audit retrieves logs generated by previous requests."""
    response = client.get("/api/v1/audit")
    assert response.status_code == 200
    logs = response.json()
    assert len(logs) >= 4  # At least 4 requests from tests above

    first_log = logs[0]
    required_fields = {
        "id", "request_id", "timestamp", "user_id", "session_id", "user_input",
        "detected_intent", "confidence_score", "routed_agent", "retrieved_memory_context",
        "agent_response", "execution_time_ms", "status", "errors"
    }
    assert required_fields.issubset(first_log.keys())


def test_audit_logs_append_only_enforcement():
    """Verifies that UPDATE or DELETE queries fail on the audit_logs table."""
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT id FROM audit_logs LIMIT 1;")
        row = cursor.fetchone()
        assert row is not None
        log_id = row[0]

        with pytest.raises(sqlite3.IntegrityError) as excinfo:
            cursor.execute("UPDATE audit_logs SET user_id = 'hacked' WHERE id = ?;", (log_id,))
            conn.commit()
        assert "Updates are not allowed on the append-only audit_logs table" in str(excinfo.value)

        with pytest.raises(sqlite3.IntegrityError) as excinfo:
            cursor.execute("DELETE FROM audit_logs WHERE id = ?;", (log_id,))
            conn.commit()
        assert "Deletions are not allowed on the append-only audit_logs table" in str(excinfo.value)


def test_memory_type_filter_validation():
    """Verifies GET /api/v1/memory rejects invalid memory type values with HTTP 400."""
    response = client.get("/api/v1/memory?user_id=usr_test_1&type=invalid_type")
    assert response.status_code == 400
    assert "short_term" in response.json()["detail"] or "long_term" in response.json()["detail"]


def test_memory_short_term_filter():
    """Verifies the short_term filter on GET /api/v1/memory returns only STM records."""
    response = client.get("/api/v1/memory?user_id=usr_test_1&type=short_term")
    assert response.status_code == 200
    data = response.json()
    for item in data:
        assert item["memory_type"] == "short_term"


def test_memory_long_term_filter():
    """Verifies the long_term filter on GET /api/v1/memory returns only LTM records."""
    response = client.get("/api/v1/memory?user_id=usr_test_1&type=long_term")
    assert response.status_code == 200
    data = response.json()
    for item in data:
        assert item["memory_type"] == "long_term"
